name: DevOps CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: List Files
        run: ls

      - name: Print Success Message
        run: echo "CI Pipeline executed successfully 🚀"