<<<<<<< HEAD
name: DevOps CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: List Files
        run: ls

      - name: Print Success Message
        run: echo "CI Pipeline executed successfully 🚀"
=======
name: DevOps CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: List Files
        run: ls

      - name: Print Success Message
        run: echo "CI Pipeline executed successfully 🚀"
>>>>>>> c88ff276469d0eb2e311ff896d5aea8a4e7f1091
